USE InternetStore;

GO
CREATE PROCEDURE DropBasket
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Basket')
	BEGIN
		EXEC DROPLINKS @TABLENAME = 'Basket';
		DROP TABLE [Basket];
	END
GO