USE InternetStore;

GO
CREATE PROCEDURE DropUsrPersonalInf
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
				WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='UserPersonalInf')
		BEGIN 
			EXEC DROPLINKS @TABLENAME = 'UserPersonalInf';
			DROP TABLE UserPersonalInf;
		END
GO