USE InternetStore;

GO
CREATE PROCEDURE DropCategory
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Category')
	BEGIN
		EXEC DROPLINKS @TABLENAME = 'Category';
		DROP TABLE Category;
	END
GO