USE InternetStore;

GO
CREATE PROCEDURE DropProduct
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
				WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Product')
		BEGIN
			EXEC DROPLINKS @TABLENAME = 'Product';
			DROP TABLE Product;
		END
GO