USE InternetStore;

GO
CREATE PROCEDURE DropUser
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
				WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='User')
		BEGIN
			EXEC DROPLINKS @TABLENAME = 'User';
			DROP TABLE [User];
		END
GO