USE InternetStore;

GO
CREATE PROCEDURE DropOrder
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
				WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Order')
		BEGIN
			EXEC DROPLINKS @TABLENAME = 'Order';
			DROP TABLE [Order];
		END
GO