USE InternetStore;

GO
CREATE PROCEDURE DropRole
AS
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
				WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Role')
		BEGIN
			EXEC DROPLINKS @TABLENAME = 'Role';
			DROP TABLE Role;
		END
GO